pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                checkout scm
                sh 'pwd'
                sh 'cd book-discovery-app/bc-5-backend/book-management-service && mvn -B -DskipTests clean package'
                sh 'cd book-discovery-app/bc-5-frontend && npm install && npm run build'


            }
        }
        stage('Test') {
            steps {
                sh 'pwd'
                sh 'cd book-discovery-app/bc-5-backend/book-management-service && mvn test'
                sh 'cd book-discovery-app/bc-5-frontend && npm run test'
            }
        }
    }
}
